# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flixup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flixup
  pod "AlamofireImage"


  target 'FlixupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixupUITests' do
    # Pods for testing
  end

end
